### ISSUE TITLE
安卓自检无法显示

### ISSUE THREAD

**Issue by jak1256** [Kabuda-czh/koishi-plugin-kbot#11]
![Screenshot_20230509_014110](https://user-images.githubusercontent.com/129949450/236896382-15d19b70-0724-4e2c-9eeb-114f395280da.jpg)
2023-05-08 18:06:12 [I] app Koishi/4.12.8
2023-05-08 18:06:12 [I] app apply plugin group:entry
2023-05-08 18:06:12 [I] app apply plugin group:basic
2023-05-08 18:06:12 [I] app apply plugin commands
2023-05-08 18:06:12 [I] app apply plugin admin
2023-05-08 18:06:12 [I] app apply plugin inspect
2023-05-08 18:06:12 [I] app apply plugin help
2023-05-08 18:06:12 [I] app apply plugin locales
2023-05-08 18:06:12 [I] app apply plugin rate-limit
2023-05-08 18:06:12 [I] app apply plugin group:console
2023-05-08 18:06:12 [I] app apply plugin console
2023-05-08 18:06:12 [I] app apply plugin dataview
2023-05-08 18:06:12 [I] app apply plugin logger
2023-05-08 18:06:12 [I] app apply plugin insight
2023-05-08 18:06:12 [I] app apply plugin sandbox
2023-05-08 18:06:12 [I] app apply plugin market
2023-05-08 18:06:12 [I] app apply plugin group:storage
2023-05-08 18:06:12 [I] app apply plugin database-sqlite
2023-05-08 18:06:12 [I] app apply plugin group:adapter
2023-05-08 18:06:12 [I] app apply plugin gocqhttp
2023-05-08 18:06:12 [I] app apply plugin adapter-onebot
2023-05-08 18:06:13 [I] app apply plugin rryth:efcbu1
2023-05-08 18:06:13 [I] app apply plugin qdvc:bin3c4
2023-05-08 18:06:13 [I] app apply plugin rr-translator:tt0wm5
2023-05-08 18:06:13 [I] app apply plugin callme:liseu5
2023-05-08 18:06:13 [I] app apply plugin blockly:d716vk
2023-05-08 18:06:13 [I] app apply plugin kbot:amguzk
2023-05-08 18:06:13 [I] app apply plugin echo:v7kotm
2023-05-08 18:06:14 [I] app apply plugin messages:rhyozy
2023-05-08 18:06:14 [I] assets missing config "selfUrl", fallback to "file:" scheme
2023-05-08 18:06:14 [I] app apply plugin send-as-image:ntmhqi
2023-05-08 18:06:12 [I] app apply plugin puppeteer:lexhpf
2023-05-08 18:06:14 [I] app server listening at http://127.0.0.1:5140
2023-05-08 18:06:12 [I] app apply plugin status
2023-05-08 18:06:12 [I] app apply plugin assets-local
2023-05-08 18:06:12 [I] app apply plugin analytics
2023-05-08 18:06:14 [I] puppeteer chrome executable found at /bin/chromium
2023-05-08 18:06:14 [I] locales loading locale zh.yml
2023-05-08 18:06:15 [I] blockly Loaded 7 plugin(s)
2023-05-08 18:06:15 [I] blockly Loading 7 plugin(s)
2023-05-08 18:06:15 [S] KBot KBot 内置插件加载完毕
2023-05-08 18:06:15 [I] gocqhttp o-cqhttp v1.0.1 © 2020 - 2023 Mrs4s[2023-05-08 18:06:15] [INFO]: 当前版本:v1.0.1
2023-05-08 18:06:15 [W] gocqhttp Protocol -> device lock is disable. http api may fail.
2023-05-08 18:06:22 [W] market timeout of 5000ms exceeded
2023-05-08 18:06:31 [W] command body 
                        TypeError: Cannot read properties of undefined (reading 'model')
                            at getCPUUsage (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:188:48)
                            at async Promise.all (index 0)
                            at async getSystemInfo (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:46:25)
                            at async _Command.<anonymous> (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/index.js:27:28)
                            at async Array.<anonymous> (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1681:14)
                            at async _Command.execute (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1696:22)
                            at async /home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2266:22
                            at async Session2.withScope (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2140:14)
                            at async render (/home/koishi-app/node_modules/@satorijs/core/lib/index.cjs:73:22)
                            at async /home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:320:22

**Comment by jak1256** [comment]
2023-05-08 18:06:12 [I] app Koishi/4.12.8
2023-05-08 18:06:12 [I] app apply plugin group:entry
2023-05-08 18:06:12 [I] app apply plugin group:basic
2023-05-08 18:06:12 [I] app apply plugin commands
2023-05-08 18:06:12 [I] app apply plugin admin
2023-05-08 18:06:12 [I] app apply plugin inspect
2023-05-08 18:06:12 [I] app apply plugin help
2023-05-08 18:06:12 [I] app apply plugin locales
2023-05-08 18:06:12 [I] app apply plugin rate-limit
2023-05-08 18:06:12 [I] app apply plugin group:console
2023-05-08 18:06:12 [I] app apply plugin console
2023-05-08 18:06:12 [I] app apply plugin dataview
2023-05-08 18:06:12 [I] app apply plugin logger
2023-05-08 18:06:12 [I] app apply plugin insight
2023-05-08 18:06:12 [I] app apply plugin sandbox
2023-05-08 18:06:12 [I] app apply plugin market
2023-05-08 18:06:12 [I] app apply plugin group:storage
2023-05-08 18:06:12 [I] app apply plugin database-sqlite
2023-05-08 18:06:12 [I] app apply plugin group:adapter
2023-05-08 18:06:12 [I] app apply plugin gocqhttp
2023-05-08 18:06:12 [I] app apply plugin adapter-onebot
2023-05-08 18:06:13 [I] app apply plugin rryth:efcbu1
2023-05-08 18:06:13 [I] app apply plugin qdvc:bin3c4
2023-05-08 18:06:13 [I] app apply plugin rr-translator:tt0wm5
2023-05-08 18:06:13 [I] app apply plugin callme:liseu5
2023-05-08 18:06:13 [I] app apply plugin blockly:d716vk
2023-05-08 18:06:13 [I] app apply plugin kbot:amguzk
2023-05-08 18:06:13 [I] app apply plugin echo:v7kotm
2023-05-08 18:06:14 [I] app apply plugin messages:rhyozy
2023-05-08 18:06:14 [I] assets missing config "selfUrl", fallback to "file:" scheme
2023-05-08 18:06:14 [I] app apply plugin send-as-image:ntmhqi
2023-05-08 18:06:12 [I] app apply plugin puppeteer:lexhpf
2023-05-08 18:06:14 [I] app server listening at http://127.0.0.1:5140
2023-05-08 18:06:12 [I] app apply plugin status
2023-05-08 18:06:12 [I] app apply plugin assets-local
2023-05-08 18:06:12 [I] app apply plugin analytics
2023-05-08 18:06:14 [I] puppeteer chrome executable found at /bin/chromium
2023-05-08 18:06:14 [I] locales loading locale zh.yml
2023-05-08 18:06:15 [I] blockly Loaded 7 plugin(s)
2023-05-08 18:06:15 [I] blockly Loading 7 plugin(s)
2023-05-08 18:06:15 [S] KBot KBot 内置插件加载完毕
2023-05-08 18:06:15 [I] gocqhttp o-cqhttp v1.0.1 © 2020 - 2023 Mrs4s[2023-05-08 18:06:15] [INFO]: 当前版本:v1.0.1
2023-05-08 18:06:15 [W] gocqhttp Protocol -> device lock is disable. http api may fail.
2023-05-08 18:06:22 [W] market timeout of 5000ms exceeded
2023-05-08 18:06:31 [W] command body 
                        TypeError: Cannot read properties of undefined (reading 'model')
                            at getCPUUsage (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:188:48)
                            at async Promise.all (index 0)
                            at async getSystemInfo (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:46:25)
                            at async _Command.<anonymous> (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/index.js:27:28)
                            at async Array.<anonymous> (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1681:14)
                            at async _Command.execute (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1696:22)
                            at async /home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2266:22
                            at async Session2.withScope (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2140:14)
                            at async render (/home/koishi-app/node_modules/@satorijs/core/lib/index.cjs:73:22)
                            at async /home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:320:22

**Comment by jak1256** [comment]
2023-05-08 18:22:37 [I] app apply plugin dataview
2023-05-08 18:22:37 [I] app apply plugin logger
2023-05-08 18:22:37 [I] app apply plugin insight
2023-05-08 18:22:37 [I] app apply plugin market
2023-05-08 18:22:38 [I] app apply plugin sandbox
2023-05-08 18:22:38 [I] app apply plugin group:storage
2023-05-08 18:22:38 [I] app apply plugin status
2023-05-08 18:22:38 [I] app apply plugin database-sqlite
2023-05-08 18:22:38 [I] app apply plugin assets-local
2023-05-08 18:22:38 [I] app apply plugin group:adapter
2023-05-08 18:22:38 [I] app apply plugin gocqhttp
2023-05-08 18:22:38 [I] app apply plugin adapter-onebot
2023-05-08 18:22:38 [I] app apply plugin puppeteer:lexhpf
2023-05-08 18:22:38 [I] app apply plugin qdvc:bin3c4
2023-05-08 18:22:38 [I] app apply plugin rryth:efcbu1
2023-05-08 18:22:38 [I] app apply plugin rr-translator:tt0wm5
2023-05-08 18:22:38 [I] app apply plugin blockly:d716vk
2023-05-08 18:22:39 [I] app apply plugin callme:liseu5
2023-05-08 18:22:39 [I] app apply plugin kbot:amguzk
2023-05-08 18:22:39 [I] app apply plugin messages:rhyozy
2023-05-08 18:22:39 [I] app apply plugin send-as-image:ntmhqi
2023-05-08 18:22:39 [I] app apply plugin echo:v7kotm
2023-05-08 18:22:39 [I] assets missing config "selfUrl", fallback to "file:" scheme
2023-05-08 18:22:39 [I] app server listening at http://127.0.0.1:5140
2023-05-08 18:22:37 [I] app apply plugin help
2023-05-08 18:22:37 [I] app apply plugin group:basic
2023-05-08 18:22:37 [I] app apply plugin admin
2023-05-08 18:22:39 [I] puppeteer chrome executable found at /bin/chromium
2023-05-08 18:22:40 [I] locales loading locale zh.yml
2023-05-08 18:22:40 [I] blockly Loading 7 plugin(s)
2023-05-08 18:22:40 [I] blockly Loaded 7 plugin(s)
2023-05-08 18:22:40 [S] KBot KBot 内置插件加载完毕
2023-05-08 18:22:40 [I] gocqhttp o-cqhttp v1.0.1 © 2020 - 2023 Mrs4s[2023-05-08 18:22:40] [INFO]: 当前版本:v1.0.1
2023-05-08 18:22:41 [W] gocqhttp Protocol -> device lock is disable. http api may fail.
2023-05-08 18:22:52 [W] command body 
                        TypeError: Cannot read properties of undefined (reading 'model')
                            at getCPUUsage (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:188:48)
                            at async Promise.all (index 0)
                            at async getSystemInfo (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:46:25)
                            at async _Command.<anonymous> (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/index.js:27:28)
                            at async Array.<anonymous> (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1681:14)
                            at async _Command.execute (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1696:22)
                            at async /home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2266:22
                            at async Session2.withScope (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2140:14)
                            at async render (/home/koishi-app/node_modules/@satorijs/core/lib/index.cjs:73:22)
                            at async /home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:320:22
2023-05-08 18:24:29 [W] command body 
                        TypeError: Cannot read properties of undefined (reading 'model')
                            at getCPUUsage (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:188:48)
                            at async Promise.all (index 0)
                            at async getSystemInfo (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/utils/index.js:46:25)
                            at async _Command.<anonymous> (/home/koishi-app/node_modules/koishi-plugin-kbot/lib/basic/status/index.js:27:28)
                            at async Array.<anonymous> (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1681:14)
                            at async _Command.execute (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1696:22)
                            at async /home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2266:22
                            at async Session2.withScope (/home/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2140:14)
                            at async render (/home/koishi-app/node_modules/@satorijs/core/lib/index.cjs:73:22)
                            at async /home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:320:22
