### ISSUE TITLE
Arm 架构机器 运行 kbot 订阅主播信息出错

### ISSUE THREAD

**Issue by xixi-furry** [Kabuda-czh/koishi-plugin-kbot#21]
指令：.bilibili -a 6524821

bot消息提示：请求失败，请检查 uid 是否正确或重试获取 6524821 信息失败: [[object Object]]

koishi日志：
```
KBot-bilibili-dynamic Error: 获取 6524821 信息失败: [[object Object]]
                            at fetchUserInfo (/opt/koishi/koishi-app/node_modules/koishi-plugin-kbot/lib/plugins/bilibili/dynamic/common.js:21:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Object.bilibiliAdd [as add] (/opt/koishi/koishi-app/node_modules/koishi-plugin-kbot/lib/plugins/bilibili/dynamic/common.js:28:26)
                            at async Array.<anonymous> (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1682:14)
                            at async _Command.execute (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1697:22)
                            at async /opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2267:22
                            at async Session2.withScope (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2141:14)
                            at async next (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:887:16)
                            at async next (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:887:16)
                            at async next (/opt/koishi/koishi-app/node_modules/@koishijs/core/lib/index.cjs:887:16)
```

**Comment by Kabuda-czh** [comment]
已经定位问题且修复, 等待下个版本发版

**Comment by Kabuda-czh** [comment]
已修复, 但此接口会时不时出现 403, 这个是 B站 自身接口异常, 需要等待 B站内部修复

**Comment by Kabuda-czh** [comment]
已更新, 修复 403 校验问题
