### ISSUE TITLE
twitter获取token失败

### ISSUE THREAD

**Issue by MsSusai** [Kabuda-czh/koishi-plugin-kbot#9]
1000|2023-05-04 08:14:56 [I] app reload plugin kbot:7n2t3z
1000|2023-05-04 08:14:56 [S] KBot KBot 内置插件加载完毕
1000|2023-05-04 08:14:56 [I] KBot-twitter-dynamic token 获取中...
1000|2023-05-04 08:14:56 [E] KBot-twitter-dynamic token 获取失败:  TypeError: Cannot read properties of undefined (reading 'page') at getTwitterToken (koishi/data/instances/default/node_modules/koishi-plugin-kbot/lib/plugins/twitter/utils/reGetToken.js:43:36) at Object.apply （koishi/data/instances/default/node_modules/koishi-plugin-kbot/lib/plugins/twitter/dynamic/index.js:102:47)
1000|2023-05-04 08:15:09 [E] KBot-twitter-dynamic error getTwitterRestId: AxiosError: Request failed with status code 403

在初始化推特模块时出现报错，然后在使用订阅指令时提示【未获取到对应 twitter 博主 ID 信息】。我在koishi控制台未发现能够添加推特token的地方，希望解决一下

**Comment by MsSusai** [comment]
已解决，确实是 puppeteer 插件的问题，多谢回复
