### ISSUE TITLE
bilibili/twitter插件图片渲染错误

### ISSUE THREAD

**Issue by XiaolanX** [Kabuda-czh/koishi-plugin-kbot#94]
不用图片模式倒是可以正常使用，但是QQ公域机器人却没办法不会转发文字，只会把图片转发过来，并且尝试获取最新推文的时候会不断重复创建一个没有名字的文件夹....puppeteer正常工作，其他插件也能正常渲染
`2024-04-29 15:56:41 [W] app Error: ENOENT: no such file or directory, mkdir ''
2024-04-29 15:57:03 [W] command dynamic.xlastest cps_niconico
                        Error: Protocol error: Connection closed. Most likely the page has been closed.
                            at assert (/home/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
                            at CdpPage.close (/home/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:864:32)
                            at getLatestTweet (/home/koishi/node_modules/koishi-plugin-dynamic-push-bot/lib/twitter/plugin/getLastestDynamic.js:62:20)
                            at async Command.<anonymous> (/home/koishi/node_modules/koishi-plugin-dynamic-push-bot/lib/twitter/plugin/getLastestDynamic.js:25:21)
                            at async Array.<anonymous> (/home/koishi/node_modules/@koishijs/core/lib/index.cjs:1149:14)
                            at async Command.execute (/home/koishi/node_modules/@koishijs/core/lib/index.cjs:1163:22)
                            at async /home/koishi/node_modules/@koishijs/core/lib/index.cjs:2182:22
                            at async Proxy.withScope (/home/koishi/node_modules/@koishijs/core/lib/index.cjs:2085:22)
                            at async next (/home/koishi/node_modules/@koishijs/core/lib/index.cjs:888:16)
                            at async next (/home/koishi/node_modules/@koishijs/core/lib/index.cjs:888:16)
2024-04-29 15:57:41 [W] app Error: ENOENT: no such file or directory, mkdir ''
2024-04-29 15:58:41 [W] app Error: ENOENT: no such file or directory, mkdir ''
2024-04-29 15:59:41 [W] app Error: ENOENT: no such file or directory, mkdir ''`
最后未知错误结束.....
环境是：
`System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (4) x64 AMD EPYC 7542 32-Core Processor

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.17.5
    Console: 5.28.4`

**Comment by XiaolanX** [comment]
QQNT的适配器是LLonebot
